spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhiyuan?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
server:
  port: 9090
mybatis:
  type-aliases-package: com.sanelee.zhiyuan.Model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml