create table `gaokao` (
                          `code` int (11),
                          `scid` int (11),
                          `sid` int (11),
                          `average` float ,
                          `year` int (4),
                          `min` float ,
                          `school_id` int (11),
                          `min_section` int (255),
                          `max` varchar (60),
                          `local_province_name` varchar (30),
                          `local_batch_name` varchar (93),
                          `spname` varchar (300),
                          `name` varchar (60),
                          `local_type_name` varchar (30),
                          `rank` int (11),
                          `proscore` varchar (765),
                          `areaname` varchar (765),
                          `is985` int (11),
                          `is211` int (11),
                          `isDoubleFirstClass` int (11)
);